repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: pretty-format-json
    -   id: detect-aws-credentials
    -   id: detect-private-key
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.1.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: flake8
-   repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
    -   id: codespell
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v7.0.0-alpha.3'
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@4.15.0
        -   eslint-config-google@0.7.1
        -   eslint-loader@1.6.1
        -   eslint-plugin-react@6.10.3
        -   babel-eslint@6.1.2
-   repo: https://github.com/pre-commit/mirrors-ruby-lint
    rev: 'v2.3.1-1'
    hooks:
    -   id: ruby-lint
-   repo: https://github.com/pre-commit/mirrors-scss-lint
    rev: 'v0.59.0'
    hooks:
    -   id: scss-lint
-   repo: git://github.com/elidupuis/mirrors-sass-lint
    rev: '5cc45653263b423398e4af2561fae362903dd45d'
    hooks:
    -   id: sass-lint
-   repo: https://github.com/PyCQA/bandit
    rev: '1.6.2'
    hooks:
    -   id: bandit
-   repo: git://github.com/guykisel/prospector-mirror
    rev: '7ff847e779347033ebbd9e3b88279e7f3a998b45'
    hooks:
    -   id: prospector
        args: [-P, .air-prospector.yaml]
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [--config, .air-pyproject.toml]
# Will link our black configuration here.
